import { Router } from 'express'
import bcrypt from 'bcryptjs'
import jwt from 'jsonwebtoken'
import { z } from 'zod'
import db from '../db.js'
import { requireAuth, optionalAuth } from '../middleware/auth.js'

const router = Router()
const publicUser = (user) => user && ({ id: user.id, fullName: user.full_name, username: user.username, email: user.email, avatarUrl: user.avatar_url, createdAt: user.created_at })
const bookView = (book) => ({ id: book.id, title: book.title, author: book.author, description: book.description, genre: book.genre, coverImageUrl: book.cover_image_url, condition: book.condition, status: book.status, createdAt: book.created_at, ownerId: book.owner_id, owner: { id: book.owner_id, fullName: book.owner_name, username: book.owner_username, avatarUrl: book.owner_avatar } })
const swapView = (row) => ({ id: row.id, bookId: row.book_id, status: row.status, createdAt: row.created_at, updatedAt: row.updated_at, book: { id: row.book_id, title: row.title, author: row.author, status: row.book_status }, requester: { id: row.requester_id, fullName: row.requester_name, username: row.requester_username }, owner: { id: row.owner_id, fullName: row.owner_name, username: row.owner_username } })
const bookJoin = `SELECT b.*, u.full_name owner_name, u.username owner_username, u.avatar_url owner_avatar FROM books b JOIN users u ON u.id = b.owner_id`
const bookSchema = z.object({ title: z.string().trim().min(2).max(140), author: z.string().trim().min(2).max(100), description: z.string().trim().min(10).max(2000), genre: z.string().trim().min(2).max(50), coverImageUrl: z.string().url().optional().or(z.literal('')), condition: z.enum(['New', 'Good', 'Fair', 'Worn']) })
const authSchema = z.object({ fullName: z.string().trim().min(2).max(100), username: z.string().trim().min(3).max(30).regex(/^[a-zA-Z0-9_.-]+$/), email: z.string().trim().email().max(150), password: z.string().min(8).max(100) })
const loginSchema = z.object({ identifier: z.string().trim().min(3), password: z.string().min(1) })
const feedbackSchema = z.object({ name: z.string().trim().min(2).max(100), email: z.string().trim().email(), type: z.enum(['Suggestion', 'Complaint']), message: z.string().trim().min(10).max(3000) })
const idParam = z.object({ id: z.coerce.number().int().positive() })
const setCookie = (response, userId) => { const token = jwt.sign({ userId }, process.env.JWT_SECRET, { expiresIn: '7d' }); response.cookie('token', token, { httpOnly: true, sameSite: 'lax', secure: process.env.NODE_ENV === 'production', maxAge: 7 * 24 * 60 * 60 * 1000 }) }
const validation = (schema, source = 'body') => (request, response, next) => { const result = schema.safeParse(request[source]); if (!result.success) return response.status(400).json({ error: result.error.issues[0]?.message || 'Invalid input' }); request.validated = result.data; next() }

router.post('/auth/register', validation(authSchema), (request, response) => { const { fullName, username, email, password } = request.validated; try { const passwordHash = bcrypt.hashSync(password, 12); const result = db.prepare('INSERT INTO users (full_name, username, email, password_hash) VALUES (?, ?, ?, ?)').run(fullName, username, email, passwordHash); setCookie(response, result.lastInsertRowid); const user = db.prepare('SELECT * FROM users WHERE id = ?').get(result.lastInsertRowid); return response.status(201).json({ user: publicUser(user) }) } catch (error) { if (error.code === 'SQLITE_CONSTRAINT_UNIQUE') return response.status(409).json({ error: 'Email or username is already registered' }); throw error } })
router.post('/auth/login', validation(loginSchema), (request, response) => { const { identifier, password } = request.validated; const user = db.prepare('SELECT * FROM users WHERE email = ? COLLATE NOCASE OR username = ? COLLATE NOCASE').get(identifier, identifier); if (!user || !bcrypt.compareSync(password, user.password_hash)) return response.status(401).json({ error: 'Wrong email/username or password' }); setCookie(response, user.id); response.json({ user: publicUser(user) }) })
router.post('/auth/logout', (_request, response) => { response.clearCookie('token'); response.status(204).end() })
router.get('/auth/me', requireAuth, (request, response) => response.json({ user: publicUser(request.user) }))

router.get('/books', optionalAuth, (request, response) => { const { search = '', genre = '', status = '' } = request.query; const clauses = []; const params = {}; if (search) { clauses.push('(b.title LIKE @search OR b.author LIKE @search OR b.description LIKE @search)'); params.search = `%${String(search).slice(0, 100)}%` } if (genre) { clauses.push('b.genre = @genre'); params.genre = String(genre).slice(0, 50) } if (status) { clauses.push('b.status = @status'); params.status = String(status).slice(0, 20) } const sql = `${bookJoin} ${clauses.length ? `WHERE ${clauses.join(' AND ')}` : ''} ORDER BY b.created_at DESC`; response.json({ books: db.prepare(sql).all(params).map(bookView) }) })
router.get('/books/:id', validation(idParam, 'params'), (request, response) => { const book = db.prepare(`${bookJoin} WHERE b.id = ?`).get(request.validated.id); if (!book) return response.status(404).json({ error: 'Book not found' }); response.json({ book: bookView(book) }) })
router.post('/books', requireAuth, validation(bookSchema), (request, response) => { const { title, author, description, genre, coverImageUrl, condition } = request.validated; const result = db.prepare('INSERT INTO books (title, author, description, genre, cover_image_url, condition, owner_id) VALUES (?, ?, ?, ?, ?, ?, ?)').run(title, author, description, genre, coverImageUrl || null, condition, request.user.id); response.status(201).json({ book: bookView(db.prepare(`${bookJoin} WHERE b.id = ?`).get(result.lastInsertRowid)) }) })
router.put('/books/:id', requireAuth, validation(idParam, 'params'), validation(bookSchema), (request, response) => { const book = db.prepare('SELECT * FROM books WHERE id = ?').get(request.validated.id); if (!book) return response.status(404).json({ error: 'Book not found' }); if (book.owner_id !== request.user.id) return response.status(403).json({ error: 'You can only edit your own books' }); const data = request.validated; db.prepare('UPDATE books SET title=?, author=?, description=?, genre=?, cover_image_url=?, condition=? WHERE id=?').run(data.title, data.author, data.description, data.genre, data.coverImageUrl || null, data.condition, book.id); response.json({ book: bookView(db.prepare(`${bookJoin} WHERE b.id = ?`).get(book.id)) }) })
router.delete('/books/:id', requireAuth, validation(idParam, 'params'), (request, response) => { const book = db.prepare('SELECT * FROM books WHERE id = ?').get(request.validated.id); if (!book) return response.status(404).json({ error: 'Book not found' }); if (book.owner_id !== request.user.id) return response.status(403).json({ error: 'You can only delete your own books' }); db.prepare('DELETE FROM books WHERE id = ?').run(book.id); response.status(204).end() })

const swapJoin = `SELECT s.*, b.title, b.author, b.status book_status, ru.full_name requester_name, ru.username requester_username, ou.full_name owner_name, ou.username owner_username FROM swap_requests s JOIN books b ON b.id=s.book_id JOIN users ru ON ru.id=s.requester_id JOIN users ou ON ou.id=s.owner_id`
router.post('/swaps', requireAuth, validation(z.object({ bookId: z.coerce.number().int().positive() })), (request, response) => { const book = db.prepare('SELECT * FROM books WHERE id = ?').get(request.validated.bookId); if (!book) return response.status(404).json({ error: 'Book not found' }); if (book.owner_id === request.user.id) return response.status(400).json({ error: 'You cannot request your own book' }); if (book.status !== 'Available') return response.status(409).json({ error: 'This book is no longer available' }); try { const result = db.prepare('INSERT INTO swap_requests (book_id, requester_id, owner_id) VALUES (?, ?, ?)').run(book.id, request.user.id, book.owner_id); db.prepare("UPDATE books SET status='Requested' WHERE id=?").run(book.id); response.status(201).json({ swap: swapView(db.prepare(`${swapJoin} WHERE s.id=?`).get(result.lastInsertRowid)) }) } catch (error) { if (error.code === 'SQLITE_CONSTRAINT_UNIQUE') return response.status(409).json({ error: 'You already requested this book' }); throw error } })
router.get('/swaps/incoming', requireAuth, (request, response) => response.json({ swaps: db.prepare(`${swapJoin} WHERE s.owner_id=? ORDER BY s.created_at DESC`).all(request.user.id).map(swapView) }))
router.get('/swaps/outgoing', requireAuth, (request, response) => response.json({ swaps: db.prepare(`${swapJoin} WHERE s.requester_id=? ORDER BY s.created_at DESC`).all(request.user.id).map(swapView) }))
const updateSwap = (action) => [requireAuth, validation(idParam, 'params'), (request, response) => { const swap = db.prepare(`${swapJoin} WHERE s.id=?`).get(request.validated.id); if (!swap) return response.status(404).json({ error: 'Swap request not found' }); if ((action === 'accept' || action === 'reject') && swap.owner_id !== request.user.id) return response.status(403).json({ error: 'Only the book owner can decide this request' }); if (action === 'complete' && swap.requester_id !== request.user.id && swap.owner_id !== request.user.id) return response.status(403).json({ error: 'You are not part of this swap' }); if (action === 'accept' && swap.status !== 'Pending') return response.status(409).json({ error: 'Only pending requests can be accepted' }); if (action === 'reject' && swap.status !== 'Pending') return response.status(409).json({ error: 'Only pending requests can be rejected' }); if (action === 'complete' && swap.status !== 'Accepted') return response.status(409).json({ error: 'Only accepted swaps can be completed' }); const nextStatus = action === 'accept' ? 'Accepted' : action === 'reject' ? 'Rejected' : 'Completed'; const transaction = db.transaction(() => { db.prepare("UPDATE swap_requests SET status=?, updated_at=CURRENT_TIMESTAMP WHERE id=?").run(nextStatus, swap.id); if (action === 'accept') { db.prepare("UPDATE books SET status='Requested' WHERE id=?").run(swap.book_id); db.prepare("UPDATE swap_requests SET status='Rejected', updated_at=CURRENT_TIMESTAMP WHERE book_id=? AND id<>? AND status='Pending'").run(swap.book_id, swap.id) } if (action === 'complete') db.prepare("UPDATE books SET status='Swapped' WHERE id=?").run(swap.book_id) }); transaction(); response.json({ swap: swapView(db.prepare(`${swapJoin} WHERE s.id=?`).get(swap.id)) }) }]
router.put('/swaps/:id/accept', ...updateSwap('accept')); router.put('/swaps/:id/reject', ...updateSwap('reject')); router.put('/swaps/:id/complete', ...updateSwap('complete'))

router.get('/users/:id', validation(idParam, 'params'), (request, response) => { const user = db.prepare('SELECT id, full_name, username, avatar_url, created_at FROM users WHERE id=?').get(request.validated.id); if (!user) return response.status(404).json({ error: 'User not found' }); const books = db.prepare(`${bookJoin} WHERE b.owner_id=? ORDER BY b.created_at DESC`).all(user.id).map(bookView); const swaps = db.prepare(`${swapJoin} WHERE s.requester_id=? OR s.owner_id=? ORDER BY s.updated_at DESC`).all(user.id, user.id).map(swapView); response.json({ user: publicUser(user), books, swaps }) })
router.put('/users/me', requireAuth, validation(z.object({ fullName: z.string().trim().min(2).max(100), avatarUrl: z.string().url().optional().or(z.literal('')) })), (request, response) => { db.prepare('UPDATE users SET full_name=?, avatar_url=? WHERE id=?').run(request.validated.fullName, request.validated.avatarUrl || null, request.user.id); response.json({ user: publicUser(db.prepare('SELECT * FROM users WHERE id=?').get(request.user.id)) }) })
router.post('/feedback', validation(feedbackSchema), (request, response) => { const { name, email, type, message } = request.validated; const result = db.prepare('INSERT INTO feedback (name,email,type,message) VALUES (?,?,?,?)').run(name, email, type, message); response.status(201).json({ feedback: { id: result.lastInsertRowid, message: 'Thanks, we received your message' } }) })

export default router
