import './style.css'

const icons = {
  book: '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 5.5A2.5 2.5 0 0 1 6.5 3H20v15H6.5A2.5 2.5 0 0 0 4 20.5v-15Z"/><path d="M4 20.5A2.5 2.5 0 0 1 6.5 18H20M8 7h8M8 11h6"/></svg>',
  swap: '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 7h14l-3-3M20 17H6l3 3"/><path d="M18 4v3M6 17v3"/></svg>',
  search: '<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="10.8" cy="10.8" r="6.8"/><path d="m16 16 5 5"/></svg>',
  moon: '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M20.4 15.2A8.7 8.7 0 0 1 8.8 3.6 8.7 8.7 0 1 0 20.4 15.2Z"/></svg>',
  sun: '<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="4"/><path d="M12 2v2M12 20v2M4.93 4.93l1.42 1.42M17.65 17.65l1.42 1.42M2 12h2M20 12h2M4.93 19.07l1.42-1.42M17.65 6.35l1.42-1.42"/></svg>',
  arrow: '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 12h14M13 6l6 6-6 6"/></svg>',
  close: '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="m6 6 12 12M18 6 6 18"/></svg>',
  menu: '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 7h16M4 12h16M4 17h16"/></svg>',
  check: '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="m5 12 4 4L19 6"/></svg>',
}

const books = [
  { id: 1, title: 'The Midnight Library', author: 'Matt Haig', genre: 'Fiction', condition: 'Like new', owner: 'Amelia R.', status: 'available', color: 'violet', desc: 'Between life and death there is a library. When Nora Seed finds herself there, she discovers a chance to try the lives she could have lived.' },
  { id: 2, title: 'Project Hail Mary', author: 'Andy Weir', genre: 'Sci-fi', condition: 'Excellent', owner: 'Daniyar K.', status: 'available', color: 'cyan', desc: 'A lone astronaut must save humanity and the planet after waking up millions of miles from home with no memory of how he got there.' },
  { id: 3, title: 'Atomic Habits', author: 'James Clear', genre: 'Self-growth', condition: 'Good', owner: 'Sofia M.', status: 'requested', color: 'amber', desc: 'An easy and proven way to build good habits and break bad ones through tiny changes that deliver remarkable results.' },
  { id: 4, title: 'Sapiens', author: 'Yuval Noah Harari', genre: 'History', condition: 'Like new', owner: 'Temur B.', status: 'available', color: 'coral', desc: 'A brief history of humankind, from the Stone Age to the age of silicon, and the stories we tell to make sense of the world.' },
  { id: 5, title: 'The Creative Act', author: 'Rick Rubin', genre: 'Art & design', condition: 'Excellent', owner: 'Laylo S.', status: 'swapped', color: 'blue', desc: 'A beautiful meditation on creativity, collaboration, and the quiet practice of making something meaningful.' },
  { id: 6, title: 'A Little Life', author: 'Hanya Yanagihara', genre: 'Fiction', condition: 'Good', owner: 'Nargiza T.', status: 'available', color: 'rose', desc: 'Four friends move to New York in search of fortune, but their bonds are tested by the shadows of the past.' },
]

const copy = {
  en: { navHome: 'Home', navAbout: 'About', navHelp: 'Help', login: 'Login', heroEyebrow: 'A better way to share stories', heroTitle: 'Pass a good book\nforward.', heroText: 'Exchange books with curious people around you. Read something wonderful, then let it travel.', explore: 'Explore books', how: 'How it works', library: 'Community library', booksFound: 'books found', search: 'Search by title, author...', allGenres: 'All genres', allAvailability: 'All availability', available: 'Available', requested: 'Requested', swapped: 'Swapped', details: 'View details', request: 'Request swap', aboutEyebrow: 'The idea', aboutTitle: 'Stories are better\nwhen they travel.', aboutText: 'On BookCrossing, you can exchange books with your friends. Read a book, pass it on, and discover new stories shared by people around you.', discover: 'Discover the ritual', helpEyebrow: 'Need a hand?', helpTitle: 'Make your next\nswap effortless.', faqTitle: 'Frequently asked', suggestion: 'Suggestion or complaint', name: 'Your name', email: 'Email address', messageType: 'Message type', suggestionOpt: 'Suggestion', complaintOpt: 'Complaint', message: 'Tell us what is on your mind...', send: 'Send message', sent: 'Thanks, we received it', footer: 'Created by Usmonov Shaxriyor — September 7, 2026', signIn: 'Sign In', signUp: 'Sign Up', username: 'Email or username', password: 'Password', fullName: 'Full name', confirm: 'Confirm password', close: 'Close' },
  ru: { navHome: 'Главная', navAbout: 'О нас', navHelp: 'Помощь', login: 'Войти', heroEyebrow: 'Лучший способ делиться историями', heroTitle: 'Передай хорошую\nкнигу дальше.', heroText: 'Обменивайтесь книгами с людьми рядом. Прочитай что-то прекрасное и позволь истории путешествовать.', explore: 'Найти книгу', how: 'Как это работает', library: 'Библиотека сообщества', booksFound: 'книг найдено', search: 'Поиск по названию, автору...', allGenres: 'Все жанры', allAvailability: 'Любой статус', available: 'Доступна', requested: 'Запрошена', swapped: 'Обменена', details: 'Подробнее', request: 'Запросить обмен', aboutEyebrow: 'Идея', aboutTitle: 'Истории лучше,\nкогда путешествуют.', aboutText: 'На BookCrossing вы можете обмениваться книгами с друзьями. Прочитайте книгу, передайте её дальше и открывайте новые истории от людей рядом.', discover: 'Открыть ритуал', helpEyebrow: 'Нужна помощь?', helpTitle: 'Следующий обмен\nбудет проще.', faqTitle: 'Частые вопросы', suggestion: 'Предложение или жалоба', name: 'Ваше имя', email: 'Электронная почта', messageType: 'Тип сообщения', suggestionOpt: 'Предложение', complaintOpt: 'Жалоба', message: 'Расскажите, что вас беспокоит...', send: 'Отправить', sent: 'Спасибо, мы получили сообщение', footer: 'Создано Усмоновым Шахриёром — 7 сентября 2026', signIn: 'Войти', signUp: 'Регистрация', username: 'Почта или имя пользователя', password: 'Пароль', fullName: 'Полное имя', confirm: 'Подтвердите пароль', close: 'Закрыть' },
  uz: { navHome: 'Bosh sahifa', navAbout: 'Biz haqimizda', navHelp: 'Yordam', login: 'Kirish', heroEyebrow: 'Hikoyalarni ulashishning yaxshi usuli', heroTitle: 'Yaxshi kitobni\noldinga uzat.', heroText: 'Atrofingizdagi kitobsevarlar bilan almashing. Ajoyib kitob o‘qing va uni sayohatga chiqaring.', explore: 'Kitoblarni ko‘rish', how: 'Bu qanday ishlaydi', library: 'Hamjamiyat kutubxonasi', booksFound: 'ta kitob topildi', search: 'Nom yoki muallif bo‘yicha izlash...', allGenres: 'Barcha janrlar', allAvailability: 'Barcha holatlar', available: 'Mavjud', requested: 'So‘ralgan', swapped: 'Almashtirilgan', details: 'Batafsil', request: 'Almashishni so‘rash', aboutEyebrow: 'G‘oya', aboutTitle: 'Hikoyalar yaxshi,\nular sayohat qilganda.', aboutText: 'BookCrossing’da do‘stlaringiz bilan kitob almashishingiz mumkin. Kitob o‘qing, uni boshqalarga bering va atrofingizdagi odamlar ulashgan yangi hikoyalarni kashf eting.', discover: 'Marosimni kashf et', helpEyebrow: 'Yordam kerakmi?', helpTitle: 'Keyingi almashuvni\nosonlashtiring.', faqTitle: 'Ko‘p so‘raladigan savollar', suggestion: 'Taklif yoki shikoyat', name: 'Ismingiz', email: 'Elektron pochta', messageType: 'Xabar turi', suggestionOpt: 'Taklif', complaintOpt: 'Shikoyat', message: 'Fikringizni yozing...', send: 'Xabar yuborish', sent: 'Rahmat, xabaringizni oldik', footer: 'Usmonov Shaxriyor tomonidan yaratildi — 2026-yil 7-sentabr', signIn: 'Kirish', signUp: 'Ro‘yxatdan o‘tish', username: 'Email yoki foydalanuvchi nomi', password: 'Parol', fullName: 'To‘liq ism', confirm: 'Parolni tasdiqlang', close: 'Yopish' },
}

let lang = 'en'
let dark = true
let activeAuthTab = 'signin'
const t = (key) => copy[lang][key]
const icon = (name) => icons[name]
const statusText = (status) => t(status)

document.querySelector('#app').innerHTML = `
  <div class="ambient ambient-one"></div><div class="ambient ambient-two"></div><div class="ambient ambient-three"></div>
  <header class="topbar glass"><a class="brand" href="#home" aria-label="BookCrossing home"><span class="brand-mark">${icon('book')}<span>${icon('swap')}</span></span><span class="brand-name">Book<span>Crossing</span></span></a><nav class="nav-links" aria-label="Primary navigation"><a href="#home" data-i18n="navHome">Home</a><a href="#about" data-i18n="navAbout">About</a><a href="#help" data-i18n="navHelp">Help</a></nav><div class="header-actions"><button class="icon-btn theme-toggle" aria-label="Toggle theme">${icon('moon')}</button><div class="language"><button class="language-btn" aria-expanded="false">EN <span>⌄</span></button><div class="language-menu"><button data-lang="en">English <b>EN</b></button><button data-lang="ru">Русский <b>RU</b></button><button data-lang="uz">O‘zbekcha <b>UZ</b></button></div></div><button class="button button-small login-btn" data-i18n="login">Login</button><button class="icon-btn menu-btn" aria-label="Open menu">${icon('menu')}</button></div></header>
  <main><section class="hero section-pad" id="home"><div class="hero-copy reveal"><div class="eyebrow"><span></span><span data-i18n="heroEyebrow">A better way to share stories</span></div><h1 data-i18n="heroTitle">Pass a good book<br>forward.</h1><p data-i18n="heroText">Exchange books with curious people around you. Read something wonderful, then let it travel.</p><div class="hero-actions"><a href="#library" class="button button-primary" data-i18n="explore">Explore books ${icon('arrow')}</a><a href="#about" class="text-link" data-i18n="how">How it works <span>↗</span></a></div><div class="social-proof"><div class="avatars"><span>AS</span><span>DK</span><span>SM</span><span>+</span></div><span>1,240 readers are exchanging today</span></div></div><div class="hero-art reveal"><div class="orbit orbit-one"></div><div class="orbit orbit-two"></div><div class="book-scene"><div class="book book-back"><span>THE<br>ART<br>OF<br>REST</span></div><div class="book book-front"><span>READ<br>WIDE.<br>LIVE<br>DEEP.</span><small>BOOKCROSSING</small></div><div class="floating-note note-one">↗ <span>Pass it on</span></div><div class="floating-note note-two"><span>Read · Share · Repeat</span></div></div></div></section>
  <section class="library section-pad" id="library"><div class="section-heading reveal"><div><div class="eyebrow"><span></span><span data-i18n="library">Community library</span></div><h2>Find your next<br><em>favorite</em> story.</h2></div><div class="section-meta"><strong id="book-count">6</strong><span data-i18n="booksFound">books found</span></div></div><div class="filters glass reveal"><div class="search-wrap">${icon('search')}<input id="search" data-i18n-placeholder="search" placeholder="Search by title, author..." /></div><select id="genre"><option value="all" data-i18n="allGenres">All genres</option><option>Fiction</option><option>Sci-fi</option><option>Self-growth</option><option>History</option><option>Art & design</option></select><select id="availability"><option value="all" data-i18n="allAvailability">All availability</option><option value="available" data-i18n="available">Available</option><option value="requested" data-i18n="requested">Requested</option><option value="swapped" data-i18n="swapped">Swapped</option></select><button class="filter-reset" id="reset-filters">Reset</button></div><div class="book-grid" id="book-grid"></div></section>
  <section class="about-section section-pad" id="about"><div class="about-visual glass reveal"><div class="exchange-illustration"><div class="illus-book illus-a">A<br>BOOK</div><div class="illus-arrow">↔</div><div class="illus-book illus-b">YOUR<br>STORY</div></div><span class="stamp">Since<br><b>2026</b></span></div><div class="about-copy reveal"><div class="eyebrow"><span></span><span data-i18n="aboutEyebrow">The idea</span></div><h2 data-i18n="aboutTitle">Stories are better<br>when they travel.</h2><p data-i18n="aboutText">On BookCrossing, you can exchange books with your friends. Read a book, pass it on, and discover new stories shared by people around you.</p><a class="text-link" href="#help" data-i18n="discover">Discover the ritual <span>↗</span></a></div></section>
  <section class="help-section section-pad" id="help"><div class="section-heading reveal"><div><div class="eyebrow"><span></span><span data-i18n="helpEyebrow">Need a hand?</span></div><h2 data-i18n="helpTitle">Make your next<br><em>swap</em> effortless.</h2></div><span class="help-icon">?</span></div><div class="help-grid"><div class="faq-list glass reveal"><h3 data-i18n="faqTitle">Frequently asked</h3><div class="faq-item active"><button>How do I list a book? <span>+</span></button><p>Open your profile, choose “List a book”, add a photo and a few details. Your book will be visible to readers nearby.</p></div><div class="faq-item"><button>How do I request a swap? <span>+</span></button><p>Find a book you love, open its details, and select Request swap. The owner will be notified.</p></div><div class="faq-item"><button>What happens after a match? <span>+</span></button><p>Coordinate a friendly hand-off in chat, then mark the swap complete so the story can keep moving.</p></div></div><form class="contact-form glass reveal" id="contact-form"><h3 data-i18n="suggestion">Suggestion or complaint</h3><label><span data-i18n="name">Your name</span><input required placeholder="Alex Morgan" /></label><label><span data-i18n="email">Email address</span><input required type="email" placeholder="alex@email.com" /></label><label><span data-i18n="messageType">Message type</span><select><option data-i18n="suggestionOpt">Suggestion</option><option data-i18n="complaintOpt">Complaint</option></select></label><label><span data-i18n="message">Tell us what is on your mind...</span><textarea required rows="3"></textarea></label><button class="button button-primary" type="submit" data-i18n="send">Send message ${icon('arrow')}</button><div class="success-message" id="success-message">${icon('check')} <span data-i18n="sent">Thanks, we received it</span></div></form></div></section></main>
  <footer class="footer section-pad"><div class="footer-top"><a class="brand" href="#home"><span class="brand-mark">${icon('book')}<span>${icon('swap')}</span></span><span class="brand-name">Book<span>Crossing</span></span></a><div class="footer-links"><a href="#about" data-i18n="navAbout">About</a><a href="#help" data-i18n="navHelp">Help</a><a href="#">Privacy Policy</a><a href="#help">Contact</a></div><div class="socials"><a href="#" aria-label="Instagram">ig</a><a href="#" aria-label="Twitter">X</a><a href="#" aria-label="Telegram">tg</a></div></div><div class="footer-bottom"><span data-i18n="footer">Created by Usmonov Shaxriyor — September 7, 2026</span><span>Made for people who pass stories on.</span></div></footer><div class="modal-backdrop" id="modal-backdrop"><div class="modal glass" id="modal-content"></div></div><div class="toast" id="toast"></div>`

const grid = document.querySelector('#book-grid')
function renderBooks() { const search = document.querySelector('#search').value.toLowerCase(); const genre = document.querySelector('#genre').value; const availability = document.querySelector('#availability').value; const visible = books.filter((book) => (!search || `${book.title} ${book.author}`.toLowerCase().includes(search)) && (genre === 'all' || book.genre === genre) && (availability === 'all' || book.status === availability)); document.querySelector('#book-count').textContent = visible.length; grid.innerHTML = visible.map((book, index) => `<article class="book-card glass reveal" style="--delay:${index * 55}ms" data-id="${book.id}"><div class="cover cover-${book.color}"><span>${book.title.split(' ').slice(0, 2).join('<br>')}</span><small>${book.author}</small><i>${book.genre}</i></div><div class="book-info"><div class="book-title-row"><div><h3>${book.title}</h3><p>${book.author}</p></div><button class="round-arrow" aria-label="View ${book.title}">${icon('arrow')}</button></div><div class="book-meta"><span>${book.condition}</span><span>·</span><span>${book.owner}</span><b class="status status-${book.status}">${statusText(book.status)}</b></div><button class="card-request" data-request="${book.id}" ${book.status !== 'available' ? 'disabled' : ''}>${book.status === 'available' ? t('request') : statusText(book.status)} ${book.status === 'available' ? icon('arrow') : ''}</button></div></article>`).join('') || `<div class="empty-state glass">No books match that search yet.</div>`; grid.querySelectorAll('.book-card').forEach((card) => card.addEventListener('click', (event) => { if (!event.target.closest('.card-request')) openBook(Number(card.dataset.id)) })); grid.querySelectorAll('[data-request]').forEach((button) => button.addEventListener('click', (event) => { event.stopPropagation(); openBook(Number(button.dataset.request), true) })); observeReveals() }
function openBook(id, requestOnly = false) { const book = books.find((item) => item.id === id); document.querySelector('#modal-content').innerHTML = requestOnly ? `<button class="modal-close" aria-label="${t('close')}">${icon('close')}</button><div class="request-modal"><div class="mini-cover cover-${book.color}">${book.title.split(' ').slice(0, 2).join('<br>')}</div><div><div class="eyebrow"><span></span>Book request</div><h2>${book.title}</h2><p>Request this copy from <strong>${book.owner}</strong>? You can arrange a hand-off after they accept.</p><button class="button button-primary" id="confirm-request">${t('request')} ${icon('arrow')}</button></div></div>` : `<button class="modal-close" aria-label="${t('close')}">${icon('close')}</button><div class="detail-modal"><div class="detail-cover cover-${book.color}"><span>${book.title.split(' ').slice(0, 2).join('<br>')}</span><small>${book.author}</small></div><div class="detail-copy"><div class="eyebrow"><span></span>${book.genre}</div><h2>${book.title}</h2><p class="detail-author">${book.author}</p><p>${book.desc}</p><div class="owner-line"><span class="owner-avatar">${book.owner.split(' ').map((part) => part[0]).join('')}</span><span>Owned by <b>${book.owner}</b></span><span class="status status-${book.status}">${statusText(book.status)}</span></div>${book.status === 'available' ? `<button class="button button-primary" id="detail-request">${t('request')} ${icon('arrow')}</button>` : ''}</div></div>`; document.querySelector('#modal-backdrop').classList.add('open'); document.querySelector('.modal-close').addEventListener('click', closeModal); document.querySelector('#confirm-request, #detail-request')?.addEventListener('click', () => { book.status = 'requested'; closeModal(); renderBooks(); showToast('Request sent. Happy reading!') }) }
function openAuth() { document.querySelector('#modal-content').innerHTML = `<button class="modal-close" aria-label="${t('close')}">${icon('close')}</button><div class="auth-modal"><div class="auth-intro"><span class="brand-mark">${icon('book')}<span>${icon('swap')}</span></span><h2>Welcome to<br>the exchange.</h2><p>Every book has another chapter after you.</p></div><div class="auth-panel"><div class="auth-tabs"><button class="${activeAuthTab === 'signin' ? 'active' : ''}" data-auth="signin">${t('signIn')}</button><button class="${activeAuthTab === 'signup' ? 'active' : ''}" data-auth="signup">${t('signUp')}</button></div><form id="auth-form">${activeAuthTab === 'signup' ? `<label>${t('fullName')}<input required></label>` : ''}<label>${t('username')}<input required type="text"></label><label>${t('password')}<input required type="password"></label>${activeAuthTab === 'signup' ? `<label>${t('confirm')}<input required type="password"></label>` : ''}<button class="button button-primary" type="submit">${activeAuthTab === 'signup' ? t('signUp') : t('signIn')} ${icon('arrow')}</button></form></div></div>`; document.querySelector('#modal-backdrop').classList.add('open'); document.querySelector('.modal-close').addEventListener('click', closeModal); document.querySelectorAll('[data-auth]').forEach((button) => button.addEventListener('click', () => { activeAuthTab = button.dataset.auth; openAuth() })); document.querySelector('#auth-form').addEventListener('submit', (event) => { event.preventDefault(); closeModal(); showToast(activeAuthTab === 'signup' ? 'Welcome to BookCrossing!' : 'Good to see you again.') }) }
function closeModal() { document.querySelector('#modal-backdrop').classList.remove('open') }
function showToast(message) { const toast = document.querySelector('#toast'); toast.textContent = message; toast.classList.add('show'); setTimeout(() => toast.classList.remove('show'), 3200) }
function applyLanguage() { document.documentElement.lang = lang; document.querySelectorAll('[data-i18n]').forEach((element) => { element.textContent = t(element.dataset.i18n) }); document.querySelectorAll('[data-i18n-placeholder]').forEach((element) => { element.placeholder = t(element.dataset.i18nPlaceholder) }); document.querySelector('.language-btn').innerHTML = `${lang.toUpperCase()} <span>⌄</span>`; renderBooks() }
function observeReveals() { const observer = new IntersectionObserver((entries) => entries.forEach((entry) => { if (entry.isIntersecting) { entry.target.classList.add('is-visible'); observer.unobserve(entry.target) } }), { threshold: 0.08 }); document.querySelectorAll('.reveal:not(.is-visible)').forEach((element) => observer.observe(element)) }

renderBooks(); observeReveals()
document.querySelector('#search').addEventListener('input', renderBooks); document.querySelector('#genre').addEventListener('change', renderBooks); document.querySelector('#availability').addEventListener('change', renderBooks); document.querySelector('#reset-filters').addEventListener('click', () => { document.querySelector('#search').value = ''; document.querySelector('#genre').value = 'all'; document.querySelector('#availability').value = 'all'; renderBooks() }); document.querySelector('.login-btn').addEventListener('click', openAuth); document.querySelector('.modal-backdrop').addEventListener('click', (event) => { if (event.target.id === 'modal-backdrop') closeModal() }); document.addEventListener('keydown', (event) => { if (event.key === 'Escape') closeModal() }); document.querySelector('.theme-toggle').addEventListener('click', () => { dark = !dark; document.documentElement.dataset.theme = dark ? 'dark' : 'light'; document.querySelector('.theme-toggle').innerHTML = icon(dark ? 'moon' : 'sun') }); document.querySelector('.language-btn').addEventListener('click', () => document.querySelector('.language').classList.toggle('open')); document.querySelectorAll('[data-lang]').forEach((button) => button.addEventListener('click', () => { lang = button.dataset.lang; document.querySelector('.language').classList.remove('open'); applyLanguage() })); document.querySelector('.menu-btn').addEventListener('click', () => document.querySelector('.nav-links').classList.toggle('mobile-open')); document.querySelectorAll('.nav-links a').forEach((link) => link.addEventListener('click', () => document.querySelector('.nav-links').classList.remove('mobile-open'))); document.querySelectorAll('.faq-item button').forEach((button) => button.addEventListener('click', () => button.parentElement.classList.toggle('active'))); document.querySelector('#contact-form').addEventListener('submit', (event) => { event.preventDefault(); document.querySelector('#success-message').classList.add('show'); event.target.reset(); setTimeout(() => document.querySelector('#success-message').classList.remove('show'), 4000) })
